### PR TITLE
ci(Windows): cache xmake dependencies

### PR DESCRIPTION
**Pull request by poirierlouis**
Add `restore-keys` to reuse partial caches.

### CODE REVIEW

**Comment by poirierlouis** [comment]
I can see that protobuf-cpp is the [culprit](https://github.com/tiltedphoques/CyberpunkMP/actions/runs/12091733657/job/33720496641?pr=36#step:6:12)...

**Comment by maximegmd** [comment]
> I can see that `protobuf` is the [culprit](https://github.com/tiltedphoques/CyberpunkMP/actions/runs/12091733657/job/33720496641?pr=36#step:6:12)...

it always is lol

**Comment by poirierlouis** [comment]
> > I can see that `protobuf` is the [culprit](https://github.com/tiltedphoques/CyberpunkMP/actions/runs/12091733657/job/33720496641?pr=36#step:6:12)...
> 
> it always is lol

Is there no way to cache it, maybe manually? 10min is such a waste... I'm not sure, downloaded archive is about `protobuf` and `protobuf-cpp`?

**Comment by maximegmd** [comment]
I am not sure why that happens, I am not very knowledgeable when it comes to caching in github. We are probably doing it incorrectly but I can't really say why...

**Comment by poirierlouis** [comment]
I'm learning too and couldn't find an explanation so far. I'll keep tweaking settings and see what the runner logs out...

**Review by maximegmd — APPROVED** [review]

**Pull request merged**
